### ISSUE TITLE
problem with abundance treshold

### ISSUE THREAD

**Issue by SilasK** [borenstein-lab/empanada#1]
I had the same error without specifying the threshold, so I assume it is an internal error.  

![image](https://cloud.githubusercontent.com/assets/7523034/23992355/d726cdc8-0a3c-11e7-99f3-4b57c94c8641.png)

Sorry for the output format.

**Comment by elhanan-borenstein** [comment]
Can you please send us the data files you used when encountering this problem?? Elhanan

**Comment by nick-youngblut** [comment]
I believe that I'm getting the same threshold error:

```
$ run_empanada.py -ko simulated_ko_relative_abundance.tab -ko2path KOvsPATHWAY_BACTERIAL_KEGG_2013_07_15.tab -o TEST.tsv -map by_avg_abundance -fraction -leave_one_ko_out_pathway_support -use_only_non_overlapping_genes

Reading files...
/ebio/abt3_projects/software/dev/miniconda3_dev/envs/empanada/lib/python3.7/site-packages/empanada-0.0.2-py3.7.egg/empanada/compute_pathway_abundance.py:46: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
/ebio/abt3_projects/software/dev/miniconda3_dev/envs/empanada/lib/python3.7/site-packages/empanada-0.0.2-py3.7.egg/empanada/compute_pathway_abundance.py:60: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
Done.
Adding 'unknown' pathway assignment for 1601 KOs with no pathway...
Adding 'zero abundance' vectors for 7439 KOs with no abundance values...
number of samples is 20
number of KOs is 11012
number of pathways is 147
Traceback (most recent call last):
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/empanada/bin/run_empanada.py", line 4, in <module>
    __import__('pkg_resources').run_script('empanada==0.0.2', 'run_empanada.py')
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/empanada/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/empanada/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(script_code, namespace, namespace)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/empanada/lib/python3.7/site-packages/empanada-0.0.2-py3.7.egg/EGG-INFO/scripts/run_empanada.py", line 83, in <module>
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/empanada/lib/python3.7/site-packages/empanada-0.0.2-py3.7.egg/empanada/compute_pathway_abundance.py", line 213, in main
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/empanada/lib/python3.7/site-packages/numpy/core/arrayprint.py", line 246, in set_printoptions
    floatmode, legacy)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/empanada/lib/python3.7/site-packages/numpy/core/arrayprint.py", line 93, in _make_options_dict
    raise ValueError("threshold must be numeric and non-NAN, try "
ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation
```

Inputting a threshold value (eg., `-threshold 0.0`) results in the same error. It might be a numpy version issue. 

 I'm running `empanada` cloned from the master branch today. My conda environment:
```
# Name                    Version                   Build  Channel
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py37_0    conda-forge
libblas                   3.8.0                4_openblas    conda-forge
libcblas                  3.8.0                4_openblas    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 8.2.0                hdf63c60_1
libgfortran               3.0.0                         1    conda-forge
liblapack                 3.8.0                4_openblas    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.16.2           py37h8b7e671_1    conda-forge
openblas                  0.3.5                ha44fe06_0    conda-forge
openssl                   1.1.1b               h14c3975_1    conda-forge
pandas                    0.24.2           py37hf484d3e_0    conda-forge
pip                       19.0.3                   py37_0    conda-forge
python                    3.7.2                h381d211_0    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2018.9                     py_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
setuptools                40.8.0                   py37_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlite                    3.26.0            h67949de_1001    conda-forge
tk                        8.6.9             h84994c4_1000    conda-forge
wheel                     0.33.1                   py37_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
```

conda info:
```
     active environment : empanada
    active env location : /ebio/abt3_projects/software/dev/miniconda3_dev/envs/empanada
            shell level : 1
       user config file : /ebio/abt3/nyoungblut/.condarc
 populated config files : /ebio/abt3_projects/software/dev/miniconda3_dev/.condarc
                          /ebio/abt3/nyoungblut/.condarc
          conda version : 4.6.8
    conda-build version : 3.11.0
         python version : 3.6.7.final.0
       base environment : /ebio/abt3_projects/software/dev/miniconda3_dev  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/leylabmpi/linux-64
                          https://conda.anaconda.org/leylabmpi/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/qiime2/linux-64
                          https://conda.anaconda.org/qiime2/noarch
          package cache : /ebio/abt3_projects/software/dev/miniconda3_dev/pkgs
                          /ebio/abt3/nyoungblut/.conda/pkgs
       envs directories : /ebio/abt3_projects/software/dev/miniconda3_dev/envs
                          /ebio/abt3/nyoungblut/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.8 requests/2.18.4 CPython/3.6.7 Linux/4.9.127 ubuntu/18.04.1 glibc/2.27
                UID:GID : 6354:350
             netrc file : None
           offline mode : False
```

**Comment by nick-youngblut** [comment]
At least for numpy v 1.16.2, in appears that the following changes should be made to `compute_pathway_abundance.py`:

```
line46 => ko_abun_data = pd.read_csv(args['ko_abun_file'], sep='\t', index_col=0, dtype={0: str})
line60 => ko_to_pathway_data = pd.read_csv(args['ko_to_pathway_file'], sep='\t', index_col=0, dtype={0: str})
line213 => np.set_printoptions(threshold=sys.maxsize)
```

Given the small number of changes, I haven't submitted a pull request, but I can if you'd like.

**Comment by engal** [comment]
Thanks for bringing this issue to our attention! In the near future, we will release an updated version with this fix both here and via PIP. For now though, we would suggest either making the change you've indicated locally, or using a downgraded version of numpy in the environment you're running EMPANADA.

**Comment by jzrapp** [comment]
Hi, 

I'm receiving the same error, even when downgrading... do you have an idea what else I could try?

```
jzrapp$ test_empanada.py
Path to examples:/opt/anaconda2/envs/empanada/lib/python3.7/site-packages/empanada
Reading files...
Done.
Adding 'unknown' pathway assignment for 1601 KOs with no pathway...
Adding 'zero abundance' vectors for 7439 KOs with no abundance values...
number of samples is 20
number of KOs is 11012
number of pathways is 147
Traceback (most recent call last):
  File "/opt/anaconda2/envs/empanada/bin/run_empanada.py", line 83, in <module>
    main(vars(given_args))
  File "/opt/anaconda2/envs/empanada/lib/python3.7/site-packages/empanada/compute_pathway_abundance.py", line 213, in main
    np.set_printoptions(threshold=np.nan)
  File "/opt/anaconda2/envs/empanada/lib/python3.7/site-packages/numpy/core/arrayprint.py", line 246, in set_printoptions
    floatmode, legacy)
  File "/opt/anaconda2/envs/empanada/lib/python3.7/site-packages/numpy/core/arrayprint.py", line 93, in _make_options_dict
    raise ValueError("threshold must be numeric and non-NAN, try "
ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation
Testing output...
E
======================================================================
ERROR: test_is_output_correct_for_empanada (__main__.EmpanadaTestCase)
Does EMPANADA produce the correct output for the example case?
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/anaconda2/envs/empanada/bin/test_empanada.py", line 47, in test_is_output_correct_for_empanada
    output = pd.read_table('test_empanada.tab', index_col=0)
  File "/opt/anaconda2/envs/empanada/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/opt/anaconda2/envs/empanada/lib/python3.7/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/opt/anaconda2/envs/empanada/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/opt/anaconda2/envs/empanada/lib/python3.7/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/opt/anaconda2/envs/empanada/lib/python3.7/site-packages/pandas/io/parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 689, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'test_empanada.tab' does not exist: b'test_empanada.tab'

----------------------------------------------------------------------
Ran 1 test in 1.843s

```

I downgraded to numpy 1.16.1 in my working environment:

```
jzrapp$ conda list
# packages in environment at /opt/anaconda2/envs/empanada:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl  
ca-certificates           2019.11.27                    0  
certifi                   2019.11.28               py37_0  
empanada                  0.0.2                    pypi_0    pypi
intel-openmp              2019.4                      233  
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20181209         hb402a30_0  
libffi                    3.2.1                         1    bioconda
libgfortran               3.0.1                h93005f0_2  
mkl                       2019.4                      233  
mkl-service               2.3.0            py37hfbe908c_0  
mkl_fft                   1.0.15           py37h5e564d8_0  
mkl_random                1.1.0            py37ha771720_0  
ncurses                   6.1                  h0a44026_1  
numpy                     1.16.1           py37hacdab7b_1  
numpy-base                1.16.1           py37h6575580_1  
openssl                   1.1.1d               h1de35cc_3  
pandas                    0.25.3           py37h0a44026_0  
pip                       19.3.1                   py37_0  
python                    3.7.5                h359304d_0  
python-dateutil           2.8.1                      py_0  
pytz                      2019.3                     py_0  
readline                  7.0                  h1de35cc_5  
setuptools                42.0.2                   py37_0  
six                       1.13.0                   py37_0  
sqlite                    3.30.1               ha441bb4_0  
tk                        8.6.8                ha441bb4_0  
wheel                     0.33.6                   py37_0  
xz                        5.2.4                h1de35cc_4  
zlib                      1.2.11               h1de35cc_3  
```

Thanks,
Josephine
